### ISSUE TITLE
Assignment 6

### ISSUE THREAD

**Issue by eelmstrom** [eelmstrom/Assignment-6#1]
In this assignment, I created an rmarkdown document to export to a .pdf file. 

I had a few issues with the assignment. 

1) R is having trouble finding ghostscript which is apparently used by tinytex for the function pdf_crop. This is the warning:

Error: LaTeX failed to compile hw_06_template.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See hw_06_template.log for more info.
In addition: Warning message:
In has_crop_tools() :
Tool(s) not installed or not in PATH: ghostcript
-> As a result, figure cropping will be disabled.
Execution halted

I was able to fix this by setting a path to the folder where ghostscript sits... But I have run this line of code every time I open RStudio:

 Sys.setenv(R_GSCMD="C:/Program Files/gs/gs9.53.3/bin/gswin64.exe")

2. I can't assign anyone but myself to this issue... Struggles! Hopefully Mark you can see this as a collaborator instead.

**Comment by mdscheuerell** [comment]
I'm sorry this was such a struggle, Liz. You definitely should not need to run that line of code every time before it will work. Here are 2 things I'd suggest you try:

1) Install PDFcrop (info [here](http://pdfcrop.sourceforge.net/))

2) Try switching to a different engine for knitting pdf's in RStudio by going into `Tools > Global Options... > Sweave` (see image below)

<img width="588" alt="Screen Shot 2021-03-01 at 5 12 21 AM" src="https://user-images.githubusercontent.com/5048528/109501848-0b902a80-7a4d-11eb-88b3-17288d325e9a.png">

**Comment by eelmstrom** [comment]
Thanks Mark!

Unfortunately, now I get this error when I try to knit...

[1] 127
Warning message:
In system(paste0("rmarkdown::render '", input, "'")) :
  'rmarkdown::render' not found

Would you have time to Zoom to make sure I'm doing things correctly at some
point this week?

Thanks for your help!
Liz

**Comment by mdscheuerell** [comment]
Hi Liz. Yes, let's find a time to discuss. How about Wed after 1:00?

**Comment by eelmstrom** [comment]
Ok great! How does 1:30 sound?

**Comment by mdscheuerell** [comment]
Sounds good. Can you email me a Zoom link?

**Comment by mdscheuerell** [comment]
Nice job wrapping this up!
